### ISSUE TITLE
使用时上次连接时间一直提示“尚未开始”

### ISSUE THREAD

**Issue by Neight99** [GensouSakuya/S1_Auto_Refresh#8]
看了下log，提示308了。

远程服务器返回错误: (308) Permanent Redirect。

**Comment by GensouSakuya** [comment]
感谢反馈，前段时间已经修复了，原来的地址/2b会被重定向，改成/2b/就正常了

**Comment by Neight99** [comment]
好像依然会报308，报错的堆栈是这样的。
{"ClassName":"System.Net.WebException","Message":"远程服务器返回错误: (308) Permanent Redirect。","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   在 System.Net.HttpWebRequest.GetResponse()\r\n   在 Core.HttpHelper.GetHtml(String url, Boolean isGet, CookieContainer cookies, String body, CustomEncoding encoding) 位置 S1_Auto_Refresh\\obsolete\\Core\\HttpHelper.cs:行号 34\r\n   在 Core.S1Manager.Login() 位置 S1_Auto_Refresh\\obsolete\\Core\\Manager\\S1Manager.cs:行号 59\r\n   在 Core.BaseForumManager._login() 位置 S1_Auto_Refresh\\obsolete\\Core\\Manager\\BaseForumManager.cs:行号 24\r\n   在 Core.BaseForumManager.Process() 位置 S1_Auto_Refresh\\obsolete\\Core\\Manager\\BaseForumManager.cs:行号 56\r\n   在 Core.Refresher.<Start>b__20_0() 位置 S1_Auto_Refresh\\obsolete\\Core\\Refresher.cs:行号 72","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nGetResponse\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.HttpWebRequest\nSystem.Net.WebResponse GetResponse()","HResult":-2146233079,"Source":"System","WatsonBuckets":null}

**Comment by GensouSakuya** [comment]
啊，obsolete目录下的是旧版的代码，我已经没在维护了。刚翻了一下代码，有可能是这里
obsolete\Core\Manager\S1Manager.cs:60的登录地址还是http而不是https。

master分支的代码我也更新了一下，可以试试看

**Comment by Neight99** [comment]
艹 我之前编译错工程了，现在好了！
